### ISSUE TITLE
Rules based on "strength" and "entropy"

### ISSUE THREAD

**Issue by mrclay** [ircmaxell/password-policy#5]
Are you interested in these implementations for new rules? https://code.google.com/p/mrclay/source/browse/trunk/php/MrClay/NewPasswordValidator.php#300

**Comment by aik099** [comment]
After code was moved to GitHub new link is https://github.com/mrclay/old-misc/blob/master/php/MrClay/NewPasswordValidator.php#L304 .

**Comment by aik099** [comment]
@mrclay , any updates on this?

**Comment by mrclay** [comment]
Closing until I have the time to do it.
